# Generated by Django 6.0 on 2025-12-25 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrademarkApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(max_length=50, unique=True)),
                ('trademark_name', models.CharField(max_length=200)),
                ('applicant_name', models.CharField(max_length=200)),
                ('trademark_class', models.IntegerField(help_text='Class 1-45')),
                ('status', models.CharField(choices=[('received', 'Application Received'), ('sent_to_vienna', 'Sent to Vienna Codification'), ('formality_check_pass', 'Formality Check Pass'), ('formality_check_fail', 'Formality Check Fail'), ('marked_for_exam', 'Marked for Exam'), ('objected', 'Objected'), ('exam_report_issued', 'Exam Report Issued'), ('ready_for_show_cause', 'Ready for Show Cause Hearing'), ('advertised', 'Advertised in Journal'), ('registered', 'Registered'), ('refused', 'Refused'), ('withdrawn', 'Withdrawn')], default='received', max_length=50)),
                ('filing_date', models.DateField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
