# Generated by Django 6.0 on 2025-12-26 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trademarkapplication',
            name='applicant_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('startup', 'Startup / Small Enterprise'), ('body_corporate', 'Body Corporate / Company'), ('trust', 'Trust / NGO'), ('partnership', 'Partnership Firm')], default='individual', max_length=50),
        ),
        migrations.AddField(
            model_name='trademarkapplication',
            name='company_name',
            field=models.CharField(blank=True, help_text='Required if not Individual', max_length=200, null=True),
        ),
    ]
