# Generated by Django 6.0 on 2025-12-26 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
        migrations.AddField(
            model_name='service',
            name='detailed_description',
            field=models.TextField(blank=True, help_text='Full details about the service', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='documents_required',
            field=models.TextField(default='To be discussed', help_text='List of documents needed'),
        ),
        migrations.AddField(
            model_name='service',
            name='price_estimate',
            field=models.CharField(blank=True, help_text='e.g. Starts from ₹5000', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='short_description',
            field=models.CharField(blank=True, help_text='Shown on Dashboard', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, help_text='Auto-generated URL name', null=True, unique=True),
        ),
    ]
