# Generated by Django 6.0 on 2025-12-26 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_service_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trademarkapplication',
            name='service_type',
            field=models.CharField(default='New Application', max_length=200),
        ),
    ]
