# Generated by Django 6.0 on 2025-12-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_applicationdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('formation', 'Formation of Business'), ('license', 'License'), ('litigation', 'Litigation'), ('ip', 'Intellectual Property (IP)'), ('global_ip', 'Global IP')], max_length=50),
        ),
    ]
