# Generated by Django 6.0 on 2025-12-26 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_service_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationdocument',
            old_name='document_name',
            new_name='doc_type',
        ),
    ]
