# Generated by Django 6.0 on 2025-12-25 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='URL friendly name (e.g. trademark-registration)', unique=True)),
                ('short_description', models.TextField(help_text='Shown on homepage cards', max_length=300)),
                ('full_description', models.TextField(help_text='Shown on details page')),
                ('image_url', models.URLField(blank=True, help_text='Paste an image link here', max_length=500)),
                ('icon_class', models.CharField(default='fa-solid fa-gavel', help_text='FontAwesome class (e.g., fa-solid fa-file-contract)', max_length=50)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
